//! Tier 2: checked program → one C translation unit (runtime included), compiled by the system C compiler.
//!
//! Representation
//! - `int` → `bm_int`, `f64` → `double`, sized ints → `<stdint.h>` types, `bool` → `bool`.
//! - String-literal types, `undefined`, `void` and `never` are unit values (`bm_unit`).
//! - `string` → `bm_str`, arrays → `bm_arr`, maps/sets → `bm_map`, functions → `bm_fn` (closures).
//! - Records → C structs (fields sorted by symbol). Unions → `{ uint32_t tag; union { ... } u; }`
//!   with tags in member order, so `switch (s.kind)` becomes a switch on the tag.
//! - Recursive aliases → a pointer to a reference-counted box holding the unfolded value.
//!
//! Ownership: expression results are either *owned* temporaries (released at the end of the
//! statement unless moved somewhere) or *borrowed* views of existing places. Parameters are
//! borrowed; return values are owned; storing a borrowed value retains it.

mod asyncfn;
mod body;
mod calls;
mod frame;
pub(crate) mod class;
mod iface;
mod json;

use crate::ast::{self, ExprId, ItemKind};
use crate::check::{Checker, IdentFact, ModuleFacts};
use crate::diag::Diagnostic;
use crate::hash::{FxMap, FxSet};
use crate::intern::Sym;
use crate::source::Span;
use crate::types::*;
use std::fmt::Write;

pub const RUNTIME_H: &str = include_str!("../../../../runtime/barm.h");
pub const RUNTIME_C: &str = include_str!("../../../../runtime/barm.c");

const C_PREFIX: &str = "/* Generated by barm. */\n#define _GNU_SOURCE 1\n";

/// The runtime's body without its `#include "barm.h"` (the header is pasted in instead).
fn runtime_body(out: &mut String) {
    for line in RUNTIME_C.lines() {
        if line.trim_start().starts_with("#include \"barm.h\"") {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
}

/// The runtime as one C translation unit, compiled once per compiler and flags and cached.
pub fn runtime_source() -> String {
    let mut out = String::with_capacity(RUNTIME_H.len() + RUNTIME_C.len() + 64);
    out.push_str(C_PREFIX);
    out.push_str(RUNTIME_H);
    out.push('\n');
    runtime_body(&mut out);
    out
}

/// The start every generated program shares (runtime interface, includes, prelude): the build
/// precompiles it once per compiler and flags, so a program's compile parses only its own code.
pub fn fixed_prefix() -> String {
    let mut out = String::with_capacity(C_PREFIX.len() + RUNTIME_H.len() + PRELUDE.len() + 128);
    out.push_str(C_PREFIX);
    out.push_str(RUNTIME_H);
    out.push('\n');
    out.push_str("#include <math.h>\n#include <pthread.h>\n#include <stdio.h>\n#include <stdlib.h>\n");
    out.push_str(PRELUDE);
    out
}

/// A generated program plus the runtime in one file (for `--emit-c`: compiles on its own).
pub fn standalone(program: &str) -> String {
    let head = C_PREFIX.len() + RUNTIME_H.len() + 1;
    let mut out = String::with_capacity(program.len() + RUNTIME_C.len());
    out.push_str(&program[..head]);
    runtime_body(&mut out);
    out.push_str(&program[head..]);
    out
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// A program: call `main()`.
    Run,
    /// Run every `test(...)`.
    Test,
}

/// Generates the C program, or diagnostics for constructs the backend doesn't support yet.
pub fn generate(c: &mut Checker, mode: Mode) -> Result<String, Vec<Diagnostic>> {
    let mut g = Gen::new(c);
    g.program(mode);
    for msg in std::mem::take(&mut g.internal) {
        let file = g.c.modules[0].file;
        g.errors.push(Diagnostic::new("C0003", Span::new(file, 0, 0), format!("internal compiler error: {msg}")).note("note", "this is a bug in barm; please report it with the program"));
    }
    if !g.errors.is_empty() {
        g.errors.sort_by_key(|d| (d.span.file, d.span.start));
        g.errors.dedup_by(|a, b| a.span == b.span && a.message == b.message);
        return Err(g.errors);
    }
    Ok(g.assemble())
}

/// A value produced by an expression.
#[derive(Clone, Debug)]
pub(crate) struct Val {
    pub code: String,
    pub ty: TyId,
    /// An owned temporary (registered for release at the end of the statement).
    pub owned: bool,
}

impl Val {
    fn plain(code: impl Into<String>, ty: TyId) -> Val {
        Val { code: code.into(), ty, owned: false }
    }
}

/// (module, item, type arguments) of a function instance.
type InstanceKey = (u32, u32, Vec<(u32, TyId)>);

/// A generic function instance to emit.
struct Instance {
    m: u32,
    item: u32,
    subst: FxMap<u32, TyId>,
    cname: String,
}

/// A generic instantiation's type arguments (parameter → type), sorted.
pub(crate) type TypeArgs = Vec<(u32, TyId)>;

pub(crate) struct Gen<'c, 'a> {
    pub(crate) c: &'c mut Checker<'a>,
    /// Section buffers, assembled in this order.
    typedefs: String,
    structs: String,
    protos: String,
    lits: String,
    helpers: String,
    funcs: String,
    /// Class struct bodies (after records and unions: those only hold class pointers).
    pub(crate) class_structs: String,
    ctypes: FxMap<TyId, String>,
    defined: FxSet<TyId>,
    helpers_done: FxSet<(TyId, u8)>,
    descs: FxSet<TyId>,
    lit_names: FxMap<Vec<u8>, String>,
    loc_names: FxMap<String, String>,
    instances: FxMap<InstanceKey, String>,
    queue: Vec<Instance>,
    fn_values: FxMap<String, String>,
    static_insts: FxMap<(u32, u32, TypeArgs), String>,
    /// Closure environment structs (after all value structs they may contain).
    pub(crate) env_structs: String,
    consts_done: FxSet<(u32, u32)>,
    const_init: String,
    /// Running a script: its module variables are initialized by the script, in source order.
    script_module: Option<u32>,
    /// Module variables some module changes (union of the facts).
    pub(crate) mutated_globals: FxSet<(u32, u32)>,
    counter: u32,
    pub(crate) errors: Vec<Diagnostic>,
    /// Memo for `inout_leak_free`: (module, item, parameter) → leak-free.
    pub(crate) leak_free: FxMap<(u32, u32, usize), bool>,
    /// Helpers that call generated functions (emitted after them).
    pub(crate) helpers_after: Vec<String>,
    /// Backend bugs found while generating (reported instead of emitting wrong code).
    pub(crate) internal: Vec<String>,
    /// Stack of function bodies being emitted (arrows nest).
    pub(crate) bodies: Vec<body::Body>,
    // Classes (see `class.rs`).
    pub(crate) class_insts: FxMap<TyId, class::ClassInst>,
    pub(crate) class_list: Vec<TyId>,
    pub(crate) ctor_insts: FxMap<TyId, String>,
    pub(crate) method_insts: FxMap<(TyId, u32), String>,
    pub(crate) generic_method_insts: FxMap<(TyId, u32, TypeArgs), String>,
    pub(crate) dispatch_names: FxMap<(TyId, Sym), String>,
    pub(crate) dispatchers: Vec<class::Dispatcher>,
    pub(crate) dispatch_bodies: String,
    pub(crate) overridden: FxMap<(u32, Sym), bool>,
    pub(crate) isa_decls: FxSet<u32>,
    pub(crate) class_work: Vec<class::ClassWork>,
    pub(crate) statics_done: FxSet<(u32, u32)>,
    pub(crate) ctor_move_memo: FxMap<u32, Vec<bool>>,
    pub(crate) weak_memo: FxMap<u32, bool>,
    /// Helper functions whose prototypes are in `protos`, emitted with the helpers.
    pub(crate) helpers_after_decl: String,
    /// Box types whose struct bodies are still to be defined.
    pub(crate) pending_boxes: Vec<TyId>,
    /// (source type, interface type) → itab name.
    pub(crate) itabs: FxMap<(TyId, TyId), String>,
    /// (source function type, target function type) → adapter function (see `fn_adapter`).
    pub(crate) fn_adapters: FxMap<(TyId, TyId), String>,
    /// Emit `bmg_uncaught` (main can throw, or tests).
    needs_uncaught: bool,
    /// The async function whose body `function_body` emits next (see `asyncfn.rs`).
    pub(crate) pending_async: Option<(u32, u32)>,
    /// The awaited calls embedded in the async body just emitted: (union member, frame type).
    pub(crate) last_children: Vec<(String, String)>,
    /// Frame structs of async functions.
    pub(crate) frame_defs: Vec<asyncfn::FrameDef>,
}

// Helper kinds for `helpers_done`.
const H_RC: u8 = 0;
const H_EQ: u8 = 1;
const H_HASH: u8 = 2;
const H_STR: u8 = 3;
const H_INSPECT: u8 = 4;
const H_DEFAULT: u8 = 5;
const H_RESOLVE: u8 = 6;
const H_REJECT: u8 = 7;

impl<'c, 'a> Gen<'c, 'a> {
    fn new(c: &'c mut Checker<'a>) -> Self {
        Gen {
            c,
            typedefs: String::new(),
            structs: String::new(),
            protos: String::new(),
            lits: String::new(),
            helpers: String::new(),
            funcs: String::new(),
            class_structs: String::new(),
            ctypes: FxMap::default(),
            defined: FxSet::default(),
            helpers_done: FxSet::default(),
            descs: FxSet::default(),
            lit_names: FxMap::default(),
            loc_names: FxMap::default(),
            instances: FxMap::default(),
            queue: Vec::new(),
            fn_values: FxMap::default(),
            static_insts: FxMap::default(),
            env_structs: String::new(),
            consts_done: FxSet::default(),
            const_init: String::new(),
            script_module: None,
            mutated_globals: FxSet::default(),
            counter: 0,
            errors: Vec::new(),
            internal: Vec::new(),
            helpers_after: Vec::new(),
            leak_free: FxMap::default(),
            bodies: Vec::new(),
            class_insts: FxMap::default(),
            class_list: Vec::new(),
            ctor_insts: FxMap::default(),
            method_insts: FxMap::default(),
            generic_method_insts: FxMap::default(),
            dispatch_names: FxMap::default(),
            dispatchers: Vec::new(),
            dispatch_bodies: String::new(),
            overridden: FxMap::default(),
            isa_decls: FxSet::default(),
            class_work: Vec::new(),
            statics_done: FxSet::default(),
            ctor_move_memo: FxMap::default(),
            weak_memo: FxMap::default(),
            helpers_after_decl: String::new(),
            pending_boxes: Vec::new(),
            itabs: FxMap::default(),
            fn_adapters: FxMap::default(),
            needs_uncaught: false,
            pending_async: None,
            last_children: Vec::new(),
            frame_defs: Vec::new(),
        }
    }

    pub(crate) fn fresh(&mut self, prefix: &str) -> String {
        self.counter += 1;
        format!("{prefix}{}", self.counter)
    }

    pub(crate) fn unsupported(&mut self, span: Span, what: &str) {
        self.errors.push(
            Diagnostic::new("C0001", span, format!("{what} is not supported by the native backend yet"))
                .note("note", "`barm check` accepts it; code generation for it is still being built"),
        );
    }

    pub(crate) fn facts(&self, m: u32) -> &ModuleFacts {
        &self.c.facts.as_ref().expect("built with facts")[m as usize]
    }

    pub(crate) fn ast(&self, m: u32) -> &'a ast::Ast {
        &self.c.modules[m as usize].ast
    }

    pub(crate) fn sym(&self, s: Sym) -> &str {
        self.c.interner.get(s)
    }

    pub(crate) fn tget(&self, t: TyId) -> Ty {
        *self.c.types.get(t)
    }

    // ------------------------------------------------------------ program

    fn program(&mut self, mode: Mode) {
        let modules = self.c.modules;
        let mut main_fn = None;
        let mut tests = Vec::new();
        for (mi, module) in modules.iter().enumerate() {
            for (ii, item) in module.ast.items.iter().enumerate() {
                match &item.kind {
                    ItemKind::Function(f) if self.sym(f.name) == "main" && main_fn.is_none() => main_fn = Some((mi as u32, ii as u32)),
                    ItemKind::Test { name, body, .. } => tests.push((mi as u32, name.clone(), *body)),
                    _ => {}
                }
            }
        }
        for mi in 0..modules.len() {
            let globals: Vec<(u32, u32)> = self.facts(mi as u32).mutated_globals.iter().copied().collect();
            self.mutated_globals.extend(globals);
        }
        let script = modules.iter().enumerate().find(|(_, m)| m.entry && m.ast.script.is_some()).map(|(mi, m)| (mi as u32, m.ast.script.unwrap()));
        // Then the event loop: timers, tasks and servers the program started.
        let async_run = "    bm_async_run();\n";
        let mut main_body = String::new();
        match mode {
            Mode::Run if script.is_some() && self.is_async_fn(script.unwrap().0, script.unwrap().1) => {
                let (m, i) = script.unwrap();
                self.script_module = Some(m);
                let cname = self.instance(m, i, FxMap::default());
                self.async_main(&mut main_body, &cname, VOID);
            }
            Mode::Run if script.is_some() => {
                let (m, i) = script.unwrap();
                self.script_module = Some(m);
                let cname = self.instance(m, i, FxMap::default());
                let throws = self.c.sigs[&(m, i)].throws != NEVER;
                self.needs_uncaught |= throws;
                let uncaught = if throws { "    if (bmg_err) { bmg_uncaught(); return 1; }\n" } else { "" };
                let _ = writeln!(main_body, "    {cname}();\n{uncaught}{async_run}    bm_out_flush();\n    return 0;");
            }
            Mode::Run => {
                let Some((m, i)) = main_fn else {
                    self.errors.push(Diagnostic::new("C0002", crate::source::Span::new(modules[0].file, 0, 0), "no `function main()` to run"));
                    return;
                };
                let cname = self.instance(m, i, FxMap::default());
                let ret = self.c.sigs[&(m, i)].ret;
                if self.is_async_fn(m, i) {
                    let value = self.async_value_type(ret);
                    self.async_main(&mut main_body, &cname, value);
                    return self.finish_program(main_body);
                }
                let throws = self.c.sigs[&(m, i)].throws != NEVER;
                self.needs_uncaught |= throws;
                let uncaught = if throws { "    if (bmg_err) { bmg_uncaught(); return 1; }\n" } else { "" };
                if ret == INT {
                    let _ = writeln!(main_body, "    bm_int code = {cname}();\n{uncaught}{async_run}    bm_out_flush();\n    return (int)code;");
                } else {
                    let _ = writeln!(main_body, "    {cname}();\n{uncaught}{async_run}    bm_out_flush();\n    return 0;");
                }
            }
            Mode::Test => {
                self.needs_uncaught = true;
                for (m, name, body) in tests {
                    let f = self.test_fn(m, body);
                    let _ = writeln!(main_body, "    bm_test_run({}, {f});", c_string(name.as_bytes()));
                }
                let _ = writeln!(main_body, "    bm_out_flush();\n    return bm_test_summary();");
            }
        }
        self.finish_program(main_body);
    }

    /// The program's top level (an async `main` or script) runs as the first task.
    fn async_main(&mut self, out: &mut String, cname: &str, value: TyId) {
        self.needs_uncaught = true;
        let desc = self.desc(value);
        let code = if value == INT { "(int)*(bm_int *)bm_promise_value(mp)" } else { "0" };
        let _ = writeln!(
            out,
            "    bm_task *t = bm_task_new(sizeof(AF_{cname}), {cname}_task, {desc});\n    bm_promise *mp = t->promise;\n    bm_promise_retain(mp);\n    bm_task_start(t);\n    bm_async_run();\n    if (mp->state == BM_REJECTED) {{ bmg_err = mp->err; bmg_obj_retain(bmg_err); bm_promise_release(mp); bmg_uncaught(); return 1; }}\n    if (mp->state == BM_PENDING) {{ bm_promise_release(mp); bm_out_flush(); fputs(\"warning: the program's top-level await never finished\\n\", stderr); return 13; }}\n    int code = {code};\n    bm_promise_release(mp);\n    bm_out_flush();\n    return code;"
        );
    }

    fn finish_program(&mut self, main_body: String) {
        // Rejections nobody handled are reported like uncaught errors.
        self.needs_uncaught = true;
        self.helpers_after.push("static void bmg_async_retain(void *e) { bmg_obj_retain(e); }\nstatic void bmg_async_release(void *e) { bmg_obj_release(e); }\nstatic void bmg_async_report(void *e) { bmg_err = e; bmg_obj_retain(e); bmg_uncaught(); }\n".to_string());
        let _ = writeln!(self.protos, "static void bmg_async_retain(void *e);\nstatic void bmg_async_release(void *e);\nstatic void bmg_async_report(void *e);");
        if self.needs_uncaught {
            let uncaught = self.uncaught_fn();
            self.helpers_after.push(uncaught);
        }
        // Emit queued functions, constructors and methods (they may queue more); dispatch
        // functions need every instantiated class, so they're recomputed until nothing new appears.
        loop {
            while let Some(inst) = self.queue.pop() {
                self.emit_function(inst);
            }
            if let Some(w) = self.class_work.pop() {
                self.emit_class_work(w);
                continue;
            }
            if !self.refresh_dispatchers() && self.queue.is_empty() && self.class_work.is_empty() {
                break;
            }
        }
        let classes_before = self.class_list.len();
        let tables = self.emit_class_tables();
        // Tables (printing) may call methods not called elsewhere (`toString`): emit them too.
        loop {
            while let Some(inst) = self.queue.pop() {
                self.emit_function(inst);
            }
            if let Some(w) = self.class_work.pop() {
                self.emit_class_work(w);
                continue;
            }
            break;
        }
        if self.class_list.len() != classes_before {
            self.internal.push("a class was first used by a printing method".into());
        }
        while let Some(t) = self.pending_boxes.pop() {
            self.define_struct(t);
        }
        let dispatch = std::mem::take(&mut self.dispatch_bodies);
        self.helpers_after.push(dispatch);
        self.helpers_after.push(tables);
        let mut init = std::mem::take(&mut self.const_init);
        init.insert_str(0, "    bm_async_init(bmg_async_retain, bmg_async_release, bmg_async_report);\n");
        // The program runs on a thread with a 1 GiB stack (reserved, committed as used): deep
        // recursion — including freeing long linked structures — has room without per-call checks.
        let _ = writeln!(
            self.funcs,
            "static int bmg_argc; static char **bmg_argv; static int bmg_exit;\nstatic int bmg_program(void) {{\n    bm_init(bmg_argc, bmg_argv);\n{init}{main_body}}}\nstatic void *bmg_thread(void *arg) {{ (void)arg; bmg_exit = bmg_program(); return NULL; }}\nint main(int argc, char **argv) {{\n    bmg_argc = argc; bmg_argv = argv;\n    pthread_attr_t attr; pthread_t th;\n    if (pthread_attr_init(&attr) == 0 && pthread_attr_setstacksize(&attr, (size_t)1 << 30) == 0 && pthread_create(&th, &attr, bmg_thread, NULL) == 0) {{\n        pthread_join(th, NULL);\n        return bmg_exit;\n    }}\n    return bmg_program();\n}}"
        );
    }

    /// The program's C: the runtime header, the prelude and the generated code. It links
    /// against the runtime object (see `runtime_source`); `standalone` makes it self-contained.
    fn assemble(&self) -> String {
        let mut out = String::with_capacity(RUNTIME_H.len() + PRELUDE.len() + self.funcs.len() * 2);
        out.push_str(C_PREFIX);
        out.push_str(RUNTIME_H);
        out.push('\n');
        out.push_str("#include <math.h>\n#include <pthread.h>\n#include <stdio.h>\n#include <stdlib.h>\n");
        out.push_str(PRELUDE);
        let frames = self.ordered_frames();
        for s in [&self.typedefs, &self.structs, &self.class_structs, &self.env_structs, &frames, &self.lits, &self.protos, &self.helpers, &self.funcs] {
            out.push_str(s);
            out.push('\n');
        }
        out.push_str(&self.helpers_after_decl);
        for h in &self.helpers_after {
            out.push_str(h);
        }
        out
    }

    // ------------------------------------------------------------ names, literals, locations

    pub(crate) fn lit(&mut self, bytes: &[u8]) -> String {
        if let Some(n) = self.lit_names.get(bytes) {
            return format!("BMG_LIT({n})");
        }
        let n = format!("L{}", self.lit_names.len());
        let _ = writeln!(self.lits, "BMG_STR_LIT({n}, {});", c_string(bytes));
        self.lit_names.insert(bytes.to_vec(), n.clone());
        format!("BMG_LIT({n})")
    }

    /// A C string constant "file.barm:line:col" for traps.
    pub(crate) fn loc(&mut self, span: Span) -> String {
        let file = self.c.sm.get(span.file);
        let (line, col) = file.line_col(span.start);
        let text = format!("{}:{line}:{col}", file.name);
        if let Some(n) = self.loc_names.get(&text) {
            return n.clone();
        }
        let n = format!("LOC{}", self.loc_names.len());
        let _ = writeln!(self.lits, "static const char {n}[] = {};", c_string(text.as_bytes()));
        self.loc_names.insert(text, n.clone());
        n
    }

    // ------------------------------------------------------------ types

    /// Does this type own heap memory (needs retain/release)?
    pub(crate) fn is_rc(&mut self, t: TyId) -> bool {
        match self.tget(t) {
            Ty::Str | Ty::Array(_) | Ty::Map(..) | Ty::Set(_) | Ty::Func(..) | Ty::Rec(..) | Ty::Class(..) | Ty::Interface(..) | Ty::Promise(..) => true,
            Ty::Record(fs) => {
                let fs = self.c.types.fields(fs).to_vec();
                fs.iter().any(|f| self.is_rc(f.ty))
            }
            Ty::Union(ms) => {
                let ms = self.c.types.tys(ms).to_vec();
                ms.iter().any(|&m| self.is_rc(m))
            }
            _ => false,
        }
    }

    pub(crate) fn is_unit(&self, t: TyId) -> bool {
        matches!(self.tget(t), Ty::StrLit(_) | Ty::Undefined | Ty::Void | Ty::Never)
    }

    /// The C type for a Barm type; defines structs on first use.
    pub(crate) fn ctype(&mut self, t: TyId) -> String {
        if let Some(n) = self.ctypes.get(&t) {
            return n.clone();
        }
        let name: String = match self.tget(t) {
            Ty::Int => "bm_int".into(),
            Ty::F64 => "double".into(),
            Ty::F32 => "float".into(),
            Ty::I8 => "int8_t".into(),
            Ty::I16 => "int16_t".into(),
            Ty::I32 => "int32_t".into(),
            Ty::U8 => "uint8_t".into(),
            Ty::U16 => "uint16_t".into(),
            Ty::U32 => "uint32_t".into(),
            Ty::U64 => "uint64_t".into(),
            Ty::Bool => "bool".into(),
            Ty::Str => "bm_str".into(),
            Ty::StrLit(_) | Ty::Undefined | Ty::Void | Ty::Never | Ty::Error | Ty::Unknown => "bm_unit".into(),
            Ty::Array(_) => "bm_arr".into(),
            Ty::Promise(..) => "bm_promise *".into(),
            Ty::Map(..) | Ty::Set(_) => "bm_map".into(),
            Ty::Func(..) => "bm_fn".into(),
            Ty::Record(_) => {
                let n = format!("R{}{}", t.0, self.type_suffix(t));
                let _ = writeln!(self.typedefs, "typedef struct {n} {n};");
                self.ctypes.insert(t, n.clone());
                self.define_struct(t);
                return n;
            }
            Ty::Union(ms) if self.niche(t).is_some() => {
                let (pi, _) = self.niche(t).unwrap();
                let m = self.c.types.tys(ms)[pi];
                let p = self.ctype(m);
                self.ctypes.insert(t, p.clone());
                return p;
            }
            Ty::Union(_) => {
                let n = format!("U{}{}", t.0, self.type_suffix(t));
                let _ = writeln!(self.typedefs, "typedef struct {n} {n};");
                self.ctypes.insert(t, n.clone());
                self.define_struct(t);
                return n;
            }
            Ty::Rec(..) => {
                // Boxes are only used through pointers: the body (which holds the value) is defined
                // later, so types that contain the box pointer never wait for it.
                let n = format!("B{}{}", t.0, self.type_suffix(t));
                let _ = writeln!(self.typedefs, "typedef struct {n} {n};");
                let p = format!("{n}*");
                self.ctypes.insert(t, p.clone());
                self.pending_boxes.push(t);
                return p;
            }
            Ty::Class(..) => {
                let ci = self.class_inst(t);
                let n = ci.name.clone();
                let _ = writeln!(self.typedefs, "typedef struct {n} {n};");
                let p = format!("{n}*");
                self.ctypes.insert(t, p.clone());
                self.define_struct(t);
                return p;
            }
            Ty::Interface(..) => "bm_iface".into(),
            Ty::Param(_) | Ty::Namespace(_) | Ty::BuiltinNs(_) | Ty::Expect(_) => "bm_unit".into(),
        };
        self.ctypes.insert(t, name.clone());
        name
    }

    fn type_suffix(&self, t: TyId) -> String {
        match self.c.types.name_of(t) {
            Some(n) => format!("_{}", n.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect::<String>()),
            None => String::new(),
        }
    }

    /// Box struct name for a recursive alias type (without the pointer).
    pub(crate) fn box_name(&mut self, t: TyId) -> String {
        let p = self.ctype(t);
        p.trim_end_matches('*').to_string()
    }

    fn define_struct(&mut self, t: TyId) {
        if !self.defined.insert(t) {
            return;
        }
        let name = self.ctypes[&t].trim_end_matches('*').to_string();
        let mut body = String::new();
        match self.tget(t) {
            Ty::Record(fs) => {
                let fs = self.c.types.fields(fs).to_vec();
                let _ = writeln!(body, "struct {name} {{");
                if fs.is_empty() {
                    body.push_str("    bm_unit _empty;\n");
                }
                for f in &fs {
                    let ct = self.ctype(f.ty);
                    let _ = writeln!(body, "    {ct} f_{};", self.sym(f.name));
                }
                body.push_str("};\n");
            }
            Ty::Union(ms) => {
                let ms = self.c.types.tys(ms).to_vec();
                let _ = writeln!(body, "struct {name} {{\n    uint32_t tag;\n    union {{");
                let mut any = false;
                for (i, &m) in ms.iter().enumerate() {
                    if self.is_unit(m) {
                        continue;
                    }
                    any = true;
                    let ct = self.ctype(m);
                    let _ = writeln!(body, "        {ct} m{i};");
                }
                if !any {
                    body.push_str("        bm_unit _none;\n");
                }
                body.push_str("    } u;\n};\n");
            }
            Ty::Rec(..) => {
                let inner = self.c.unfold(t);
                let ct = self.ctype(inner);
                let _ = writeln!(body, "struct {name} {{\n    int64_t rc;\n    {ct} v;\n}};");
                self.class_structs.push_str(&body);
                return;
            }
            Ty::Class(..) => {
                let b = self.define_class_struct(t);
                self.class_structs.push_str(&b);
                return;
            }
            _ => {}
        }
        // Struct bodies are appended after their by-value dependencies (defined by the recursive ctype calls above).
        self.structs.push_str(&body);
    }

    /// `C | undefined` for a class `C` is a nullable pointer (`NULL` = undefined) rather than a
    /// tagged union: (index of the class member, index of `undefined`).
    pub(crate) fn niche(&self, u: TyId) -> Option<(usize, usize)> {
        let Ty::Union(ms) = self.tget(u) else { return None };
        let ms = self.c.types.tys(ms);
        if ms.len() != 2 {
            return None;
        }
        let ui = ms.iter().position(|&m| m == UNDEFINED)?;
        let pi = 1 - ui;
        matches!(self.tget(ms[pi]), Ty::Class(..)).then_some((pi, ui))
    }

    /// The tag of a union value (for `switch`).
    pub(crate) fn u_tag(&self, code: &str, u: TyId) -> String {
        match self.niche(u) {
            Some((pi, ui)) => format!("(({code}) != NULL ? {pi} : {ui})"),
            None => format!("({code}).tag"),
        }
    }

    /// Does a union value hold member `k`?
    pub(crate) fn u_is(&self, code: &str, u: TyId, k: usize) -> String {
        match self.niche(u) {
            Some((pi, _)) if k == pi => format!("(({code}) != NULL)"),
            Some(_) => format!("(({code}) == NULL)"),
            None => format!("(({code}).tag == {k})"),
        }
    }

    /// The payload of member `k` (an lvalue when `code` is one).
    pub(crate) fn u_payload(&self, code: &str, u: TyId, k: usize) -> String {
        match self.niche(u) {
            Some(_) => format!("({code})"),
            None => format!("({code}).u.m{k}"),
        }
    }

    /// A union value holding member `k` (`payload`: its C value, `None` for unit members).
    pub(crate) fn u_make(&mut self, u: TyId, k: usize, payload: Option<&str>) -> String {
        match self.niche(u) {
            Some((pi, _)) if k == pi => payload.unwrap_or("NULL").to_string(),
            Some(_) => "NULL".to_string(),
            None => {
                let ct = self.ctype(u);
                match payload {
                    Some(p) => format!("({ct}){{ .tag = {k}, .u.m{k} = {p} }}"),
                    None => format!("({ct}){{ .tag = {k} }}"),
                }
            }
        }
    }

    /// Union members in tag order.
    pub(crate) fn members(&self, t: TyId) -> Vec<TyId> {
        match self.tget(t) {
            Ty::Union(ms) => self.c.types.tys(ms).to_vec(),
            _ => vec![t],
        }
    }

    pub(crate) fn tag_of(&self, union: TyId, member: TyId) -> Option<usize> {
        self.members(union).iter().position(|&m| m == member)
    }

    /// A valid default value (used for declared-but-unassigned variables and empty payloads).
    pub(crate) fn default_value(&mut self, t: TyId) -> String {
        match self.tget(t) {
            Ty::Str => "BM_EMPTY_STR".into(),
            Ty::Array(_) => "BM_EMPTY_ARR".into(),
            Ty::Map(..) | Ty::Set(_) => "BM_EMPTY_MAP".into(),
            Ty::Func(..) => "((bm_fn){NULL, NULL})".into(),
            Ty::Promise(..) => "NULL".into(),
            Ty::Bool => "false".into(),
            Ty::Class(..) => "NULL".into(),
            Ty::Interface(..) => "((bm_iface){NULL, NULL})".into(),
            Ty::Union(_) if self.niche(t).is_some() => "NULL".into(),
            Ty::Record(_) | Ty::Union(_) | Ty::Rec(..) => {
                self.ensure_helper(t, H_DEFAULT);
                let n = self.box_name(t);
                format!("df_{n}()")
            }
            _ => "0".into(),
        }
    }

    // ------------------------------------------------------------ per-type helpers

    /// Emits (once) the helper of the given kind for `t`.
    fn ensure_helper(&mut self, t: TyId, kind: u8) {
        if !self.helpers_done.insert((t, kind)) {
            return;
        }
        let ct = self.ctype(t);
        let n = self.box_name(t);
        let mut h = String::new();
        match kind {
            H_RC => {
                let _ = writeln!(self.protos, "static void rt_{n}(void *p);\nstatic void rl_{n}(void *p);");
                let (mut rt, mut rl) = (String::new(), String::new());
                match self.tget(t) {
                    Ty::Record(fs) => {
                        let fs = self.c.types.fields(fs).to_vec();
                        for f in fs {
                            if self.is_rc(f.ty) {
                                let fname = format!("f_{}", self.sym(f.name));
                                let _ = writeln!(rt, "    {};", self.retain_code(f.ty, &format!("x->{fname}")));
                                let _ = writeln!(rl, "    {};", self.release_code(f.ty, &format!("x->{fname}")));
                            }
                        }
                    }
                    Ty::Union(ms) => {
                        let ms = self.c.types.tys(ms).to_vec();
                        rt.push_str("    switch (x->tag) {\n");
                        rl.push_str("    switch (x->tag) {\n");
                        for (i, &m) in ms.iter().enumerate() {
                            if self.is_rc(m) {
                                let _ = writeln!(rt, "    case {i}: {}; break;", self.retain_code(m, &format!("x->u.m{i}")));
                                let _ = writeln!(rl, "    case {i}: {}; break;", self.release_code(m, &format!("x->u.m{i}")));
                            }
                        }
                        rt.push_str("    default: break;\n    }\n");
                        rl.push_str("    default: break;\n    }\n");
                    }
                    Ty::Rec(..) => {
                        let inner = self.c.unfold(t);
                        rt.push_str("    if (*x) (*x)->rc++;\n");
                        if self.is_rc(inner) {
                            // Freeing a box can recurse (long lists): bounded depth, see bmg_drop_enter.
                            let rel_inner = format!("{};", self.release_code(inner, "b->v"));
                            let _ = writeln!(self.protos, "static void fb_{n}(void *p);");
                            let _ = writeln!(self.helpers_after_decl, "static void fb_{n}(void *p) {{\n    {ct} b = p;\n    {rel_inner}\n    bmg_free_small(b, sizeof(*b));\n}}");
                            let _ = writeln!(rl, "    if (*x && --(*x)->rc == 0) fb_{n}(*x);");
                        } else {
                            let _ = writeln!(rl, "    if (*x && --(*x)->rc == 0) bmg_free_small(*x, sizeof(**x));");
                        }
                    }
                    _ => {}
                }
                let _ = writeln!(h, "static void rt_{n}(void *p) {{\n    {ct} *x = p; (void)x;\n{rt}}}");
                let _ = writeln!(h, "static void rl_{n}(void *p) {{\n    {ct} *x = p; (void)x;\n{rl}}}");
            }
            H_EQ => {
                let _ = writeln!(self.protos, "static bool eq_{n}(const void *a, const void *b);");
                let mut b = String::new();
                match self.tget(t) {
                    Ty::Record(fs) => {
                        let fs = self.c.types.fields(fs).to_vec();
                        for f in fs {
                            let fname = format!("f_{}", self.sym(f.name));
                            let e = self.eq_code(f.ty, &format!("x->{fname}"), &format!("y->{fname}"));
                            let _ = writeln!(b, "    if (!({e})) return false;");
                        }
                        b.push_str("    return true;\n");
                    }
                    Ty::Union(ms) => {
                        let ms = self.c.types.tys(ms).to_vec();
                        b.push_str("    if (x->tag != y->tag) return false;\n    switch (x->tag) {\n");
                        for (i, &m) in ms.iter().enumerate() {
                            if !self.is_unit(m) {
                                let e = self.eq_code(m, &format!("x->u.m{i}"), &format!("y->u.m{i}"));
                                let _ = writeln!(b, "    case {i}: return {e};");
                            }
                        }
                        b.push_str("    default: return true;\n    }\n");
                    }
                    Ty::Rec(..) => {
                        let inner = self.c.unfold(t);
                        let e = self.eq_code(inner, "(*x)->v", "(*y)->v");
                        let _ = writeln!(b, "    return *x == *y || ({e});");
                    }
                    _ => b.push_str("    return true;\n"),
                }
                let _ = writeln!(h, "static bool eq_{n}(const void *a, const void *b) {{\n    const {ct} *x = a; const {ct} *y = b; (void)x; (void)y;\n{b}}}");
            }
            H_HASH => {
                let _ = writeln!(self.protos, "static uint64_t hs_{n}(const void *p);");
                let mut b = String::from("    uint64_t h = 0x9E3779B97F4A7C15ull;\n");
                match self.tget(t) {
                    Ty::Record(fs) => {
                        let fs = self.c.types.fields(fs).to_vec();
                        for f in fs {
                            let fname = format!("f_{}", self.sym(f.name));
                            let e = self.hash_code(f.ty, &format!("x->{fname}"));
                            let _ = writeln!(b, "    h = (h ^ ({e})) * 0x100000001B3ull;");
                        }
                    }
                    Ty::Union(ms) => {
                        let ms = self.c.types.tys(ms).to_vec();
                        b.push_str("    h ^= x->tag;\n    switch (x->tag) {\n");
                        for (i, &m) in ms.iter().enumerate() {
                            if !self.is_unit(m) {
                                let e = self.hash_code(m, &format!("x->u.m{i}"));
                                let _ = writeln!(b, "    case {i}: h = (h ^ ({e})) * 0x100000001B3ull; break;");
                            }
                        }
                        b.push_str("    default: break;\n    }\n");
                    }
                    Ty::Rec(..) => {
                        let inner = self.c.unfold(t);
                        let e = self.hash_code(inner, "(*x)->v");
                        let _ = writeln!(b, "    h ^= {e};");
                    }
                    _ => {}
                }
                b.push_str("    return h;\n");
                let _ = writeln!(h, "static uint64_t hs_{n}(const void *p) {{\n    const {ct} *x = p; (void)x;\n{b}}}");
            }
            H_STR | H_INSPECT => {
                let inspect = kind == H_INSPECT;
                let (fname, sig) = if inspect { (format!("in_{n}"), "bm_sb *sb, const void *p, int depth") } else { (format!("ts_{n}"), "bm_sb *sb, const void *p") };
                let _ = writeln!(self.protos, "static void {fname}({sig});");
                let mut b = String::new();
                match self.tget(t) {
                    Ty::Record(_) => {
                        if !inspect {
                            b.push_str("    bm_sb_push_cstr(sb, \"[object Object]\");\n");
                        } else {
                            // Node's layout (single- or multi-line) is decided by the runtime.
                            let fs = self.c.types.fields_in_order(t);
                            let names: Vec<String> = fs.iter().map(|f| c_string(self.sym(f.name).as_bytes())).collect();
                            let descs: Vec<String> = fs.iter().map(|f| self.desc(f.ty)).collect();
                            let ptrs: Vec<String> = fs.iter().map(|f| format!("&x->f_{}", self.sym(f.name))).collect();
                            if fs.is_empty() {
                                b.push_str("    bm_inspect_record(sb, depth, 0, NULL, NULL, NULL);\n");
                            } else {
                                let _ = writeln!(b, "    static const char *const names[] = {{ {} }};", names.join(", "));
                                let _ = writeln!(b, "    const bm_type *const types[] = {{ {} }};", descs.join(", "));
                                let _ = writeln!(b, "    const void *const fields[] = {{ {} }};", ptrs.join(", "));
                                let _ = writeln!(b, "    bm_inspect_record(sb, depth, {}, names, types, fields);", fs.len());
                            }
                        }
                    }
                    Ty::Union(ms) => {
                        let ms = self.c.types.tys(ms).to_vec();
                        b.push_str("    switch (x->tag) {\n");
                        for (i, &m) in ms.iter().enumerate() {
                            let place = format!("x->u.m{i}");
                            let e = if inspect { self.inspect_code(m, &place, "depth") } else { self.string_code(m, &place) };
                            let _ = writeln!(b, "    case {i}: {e}; break;");
                        }
                        b.push_str("    default: break;\n    }\n");
                    }
                    Ty::Rec(..) => {
                        let inner = self.c.unfold(t);
                        let e = if inspect { self.inspect_code(inner, "(*x)->v", "depth") } else { self.string_code(inner, "(*x)->v") };
                        let _ = writeln!(b, "    {e};");
                    }
                    _ => {}
                }
                let _ = writeln!(h, "static void {fname}({sig}) {{\n    const {ct} *x = p; (void)x; (void)sb;{}\n{b}}}", if inspect { " (void)depth;" } else { "" });
            }
            H_DEFAULT => {
                let _ = writeln!(self.protos, "static {ct} df_{n}(void);");
                let v = match self.tget(t) {
                    Ty::Record(fs) => {
                        let fs = self.c.types.fields(fs).to_vec();
                        let parts: Vec<String> = fs.iter().map(|f| {
                            let d = self.default_value(f.ty);
                            format!(".f_{} = {d}", self.sym(f.name))
                        }).collect();
                        format!("({ct}){{ {} }}", parts.join(", "))
                    }
                    Ty::Union(ms) => {
                        let ms = self.c.types.tys(ms).to_vec();
                        // Prefer the `undefined` member, else the first.
                        let i = ms.iter().position(|&m| m == UNDEFINED).unwrap_or(0);
                        if self.is_unit(ms[i]) {
                            format!("({ct}){{ .tag = {i} }}")
                        } else {
                            let d = self.default_value(ms[i]);
                            format!("({ct}){{ .tag = {i}, .u.m{i} = {d} }}")
                        }
                    }
                    Ty::Rec(..) => {
                        let inner = self.c.unfold(t);
                        let d = self.default_value(inner);
                        let bn = self.box_name(t);
                        format!("({{ {bn} *b = bmg_alloc_small(sizeof({bn})); b->rc = 1; b->v = {d}; b; }})")
                    }
                    _ => "0".into(),
                };
                let _ = writeln!(h, "static {ct} df_{n}(void) {{ return {v}; }}");
            }
            _ => {}
        }
        self.helpers.push_str(&h);
    }

    pub(crate) fn retain_code(&mut self, t: TyId, place: &str) -> String {
        match self.tget(t) {
            Ty::Str => format!("bm_str_retain({place})"),
            Ty::Array(_) => format!("bm_arr_retain({place})"),
            Ty::Map(..) | Ty::Set(_) => format!("bm_map_retain({place})"),
            Ty::Func(..) => format!("bm_env_retain(({place}).env)"),
            Ty::Promise(..) => format!("bm_promise_retain({place})"),
            Ty::Class(..) => format!("bmg_obj_retain({place})"),
            Ty::Interface(..) => format!("bm_iface_retain({place})"),
            Ty::Union(_) if self.niche(t).is_some() => format!("bmg_obj_retain({place})"),
            _ if self.is_rc(t) => {
                self.ensure_helper(t, H_RC);
                format!("rt_{}(&{place})", self.box_name(t))
            }
            _ => "(void)0".into(),
        }
    }

    pub(crate) fn release_code(&mut self, t: TyId, place: &str) -> String {
        match self.tget(t) {
            Ty::Str => format!("bm_str_release({place})"),
            Ty::Array(e) => {
                let d = self.desc(e);
                format!("bm_arr_release({place}, {d})")
            }
            Ty::Map(k, v) => {
                let (kd, vd) = (self.desc(k), self.desc(v));
                format!("bm_map_release({place}, {kd}, {vd})")
            }
            Ty::Set(k) => {
                let kd = self.desc(k);
                format!("bm_map_release({place}, {kd}, &bm_type_undefined)")
            }
            Ty::Func(..) => format!("bm_env_release(({place}).env)"),
            Ty::Promise(..) => format!("bm_promise_release({place})"),
            Ty::Class(..) => self.class_release_code(t, place),
            Ty::Interface(..) => format!("bm_iface_release({place})"),
            Ty::Union(ms) if self.niche(t).is_some() => {
                let (pi, _) = self.niche(t).unwrap();
                let m = self.c.types.tys(ms)[pi];
                self.class_release_code(m, place)
            }
            _ if self.is_rc(t) => {
                self.ensure_helper(t, H_RC);
                format!("rl_{}(&{place})", self.box_name(t))
            }
            _ => "(void)0".into(),
        }
    }

    pub(crate) fn eq_code(&mut self, t: TyId, a: &str, b: &str) -> String {
        match self.tget(t) {
            Ty::Str => format!("bm_str_eq({a}, {b})"),
            Ty::StrLit(_) | Ty::Undefined | Ty::Void | Ty::Never => "true".into(),
            Ty::Array(_) | Ty::Map(..) | Ty::Set(_) => {
                let d = self.desc(t);
                format!("({d})->eq(&({a}), &({b}))")
            }
            Ty::Func(..) => format!("(({a}).fn == ({b}).fn && ({a}).env == ({b}).env)"),
            Ty::Class(..) | Ty::Promise(..) => format!("((void *)({a}) == (void *)({b}))"),
            Ty::Interface(..) => format!("(({a}).p == ({b}).p)"),
            Ty::Union(_) if self.niche(t).is_some() => format!("((void *)({a}) == (void *)({b}))"),
            Ty::Record(_) | Ty::Union(_) | Ty::Rec(..) => {
                self.ensure_helper(t, H_EQ);
                format!("eq_{}(&({a}), &({b}))", self.box_name(t))
            }
            _ => format!("(({a}) == ({b}))"),
        }
    }

    fn hash_code(&mut self, t: TyId, p: &str) -> String {
        let d = self.desc(t);
        format!("({d})->hash(&({p}))")
    }

    /// Appends `String(x)` of the value at `place` to `sb`.
    pub(crate) fn string_code(&mut self, t: TyId, place: &str) -> String {
        match self.tget(t) {
            Ty::Str => format!("bm_sb_push_str(sb, {place})"),
            Ty::StrLit(s) => {
                let text = self.sym(s).to_string();
                format!("bm_sb_push_cstr(sb, {})", c_string(text.as_bytes()))
            }
            Ty::Int => format!("bm_sb_push_int(sb, {place})"),
            Ty::F64 | Ty::F32 => format!("bm_sb_push_f64(sb, {place})"),
            Ty::I8 | Ty::I16 | Ty::I32 | Ty::U8 | Ty::U16 | Ty::U32 => format!("bm_sb_push_int(sb, (bm_int)({place}))"),
            Ty::U64 => format!("bm_sb_push_f64(sb, (double)({place}))"),
            Ty::Bool => format!("bm_sb_push_cstr(sb, ({place}) ? \"true\" : \"false\")"),
            Ty::Undefined | Ty::Void | Ty::Never => "bm_sb_push_cstr(sb, \"undefined\")".into(),
            Ty::Array(e) => {
                let d = self.desc(e);
                format!("bm_to_str_arr(sb, {place}, {d})")
            }
            Ty::Func(..) => "bm_sb_push_cstr(sb, \"[Function]\")".into(),
            Ty::Class(..) => self.class_string_code(t, place),
            Ty::Interface(..) => format!("(({place}).t ? ({place}).t->to_str(sb, ({place}).p) : bm_sb_push_cstr(sb, \"undefined\"))"),
            Ty::Union(ms) if self.niche(t).is_some() => {
                let (pi, _) = self.niche(t).unwrap();
                let m = self.c.types.tys(ms)[pi];
                let inner = self.class_string_code(m, place);
                format!("({{ if (({place}) != NULL) {inner}; else bm_sb_push_cstr(sb, \"undefined\"); }})")
            }
            Ty::Map(..) | Ty::Set(_) => format!("({})->to_str(sb, &({place}))", self.desc(t)),
            Ty::Promise(..) => "bm_sb_push_cstr(sb, \"[object Promise]\")".into(),
            _ => {
                self.ensure_helper(t, H_STR);
                format!("ts_{}(sb, &({place}))", self.box_name(t))
            }
        }
    }

    /// Appends console.log formatting of the value at `place` to `sb`.
    pub(crate) fn inspect_code(&mut self, t: TyId, place: &str, depth: &str) -> String {
        match self.tget(t) {
            Ty::Str => format!("bm_inspect_str(sb, {place}, {depth})"),
            Ty::StrLit(s) => {
                let lit = self.lit(self.sym(s).to_string().as_bytes());
                format!("bm_inspect_str(sb, {lit}, {depth})")
            }
            Ty::Int | Ty::F64 | Ty::F32 | Ty::I8 | Ty::I16 | Ty::I32 | Ty::U8 | Ty::U16 | Ty::U32 | Ty::U64 | Ty::Bool | Ty::Undefined | Ty::Void | Ty::Never => {
                self.string_code(t, place)
            }
            Ty::Promise(..) => format!("bm_type_promise.inspect(sb, &({place}), {depth})"),
            Ty::Array(e) => {
                let d = self.desc(e);
                format!("bm_inspect_arr(sb, {place}, {d}, {depth})")
            }
            Ty::Map(k, v) => {
                let (kd, vd) = (self.desc(k), self.desc(v));
                format!("bm_map_inspect(sb, {place}, {kd}, {vd}, {depth})")
            }
            Ty::Set(k) => {
                let kd = self.desc(k);
                format!("bm_set_inspect(sb, {place}, {kd}, {depth})")
            }
            Ty::Func(..) => "bm_sb_push_cstr(sb, \"[Function (anonymous)]\")".into(),
            Ty::Class(..) => format!("bmg_obj_inspect(sb, (void *)({place}), {depth})"),
            Ty::Interface(..) => format!("(({place}).t ? ({place}).t->inspect(sb, ({place}).p, {depth}) : bm_sb_push_cstr(sb, \"undefined\"))"),
            Ty::Union(_) if self.niche(t).is_some() => format!("({{ if (({place}) != NULL) bmg_obj_inspect(sb, (void *)({place}), {depth}); else bm_sb_push_cstr(sb, \"undefined\"); }})"),
            _ => {
                self.ensure_helper(t, H_INSPECT);
                format!("in_{}(sb, &({place}), {depth})", self.box_name(t))
            }
        }
    }

    /// A `const bm_type *` expression describing `t` (for containers and printing).
    pub(crate) fn desc(&mut self, t: TyId) -> String {
        match self.tget(t) {
            Ty::Int => return "&bm_type_int".into(),
            Ty::F64 => return "&bm_type_f64".into(),
            Ty::F32 => return "&bm_type_f32".into(),
            Ty::Bool => return "&bm_type_bool".into(),
            Ty::Str => return "&bm_type_str".into(),
            Ty::I8 => return "&bm_type_i8".into(),
            Ty::I16 => return "&bm_type_i16".into(),
            Ty::I32 => return "&bm_type_i32".into(),
            Ty::U8 => return "&bm_type_u8".into(),
            Ty::U16 => return "&bm_type_u16".into(),
            Ty::U32 => return "&bm_type_u32".into(),
            Ty::U64 => return "&bm_type_u64".into(),
            Ty::Undefined | Ty::Void | Ty::Never | Ty::Error | Ty::Unknown => return "&bm_type_undefined".into(),
            Ty::Promise(..) => return "&bm_type_promise".into(),
            _ => {}
        }
        let key = self.desc_key(t);
        if self.descs.insert(t) {
            let ct = self.ctype(t);
            let _ = writeln!(self.protos, "static const bm_type {key};");
            // Descriptor wrappers with the runtime's void* signatures.
            let rc = self.is_rc(t);
            let (rt, rl) = if rc {
                let r = self.retain_code(t, &format!("*({ct} *)p"));
                let l = self.release_code(t, &format!("*({ct} *)p"));
                let _ = writeln!(self.helpers, "static void {key}_rt(void *p) {{ {r}; }}\nstatic void {key}_rl(void *p) {{ {l}; }}");
                (format!("{key}_rt"), format!("{key}_rl"))
            } else {
                ("NULL".into(), "NULL".into())
            };
            let eq = self.eq_code(t, &format!("*(const {ct} *)a"), &format!("*(const {ct} *)b"));
            let hash = match self.tget(t) {
                Ty::Class(..) => "((uint64_t)(uintptr_t)(*(void *const *)p) * 0x9E3779B97F4A7C15ull)".into(),
                Ty::Interface(..) => "((uint64_t)(uintptr_t)(((const bm_iface *)p)->p) * 0x9E3779B97F4A7C15ull)".into(),
                Ty::Union(_) if self.niche(t).is_some() => "((uint64_t)(uintptr_t)(*(void *const *)p) * 0x9E3779B97F4A7C15ull)".into(),
                Ty::Record(_) | Ty::Union(_) | Ty::Rec(..) => {
                    self.ensure_helper(t, H_HASH);
                    format!("hs_{}(p)", self.box_name(t))
                }
                Ty::StrLit(_) => "0".into(),
                _ => "0".into(),
            };
            let ts = self.string_code(t, &format!("*(const {ct} *)p"));
            let ins = self.inspect_code(t, &format!("*(const {ct} *)p"), "depth");
            let extra = match self.tget(t) {
                Ty::Array(e) => {
                    let d = self.desc(e);
                    format!("static uint64_t {key}_hs2(const void *p) {{ const bm_arr *a = p; uint64_t h = 1469598103934665603ull; for (bm_int i = 0; i < bm_arr_len(*a); i++) h = (h ^ ({d})->hash(a->p->data + i * ({d})->size)) * 1099511628211ull; return h; }}\nstatic bool {key}_eq2(const void *x, const void *y) {{ const bm_arr *a = x, *b = y; bm_int n = bm_arr_len(*a); if (n != bm_arr_len(*b)) return false; if (a->p == b->p) return true; for (bm_int i = 0; i < n; i++) if (!({d})->eq(a->p->data + i * ({d})->size, b->p->data + i * ({d})->size)) return false; return true; }}\n")
                }
                Ty::Map(k, v) => {
                    let (kd, vd) = (self.desc(k), self.desc(v));
                    format!("static uint64_t {key}_hs2(const void *p) {{ return (uint64_t)bm_map_size(*(const bm_map *)p); }}\nstatic bool {key}_eq2(const void *x, const void *y) {{ return bm_map_eq(*(const bm_map *)x, *(const bm_map *)y, {kd}, {vd}); }}\n")
                }
                Ty::Set(k) => {
                    let kd = self.desc(k);
                    format!("static uint64_t {key}_hs2(const void *p) {{ return (uint64_t)bm_map_size(*(const bm_map *)p); }}\nstatic bool {key}_eq2(const void *x, const void *y) {{ return bm_map_eq(*(const bm_map *)x, *(const bm_map *)y, {kd}, &bm_type_undefined); }}\n")
                }
                _ => String::new(),
            };
            let (eq_fn, hash_fn) = if extra.is_empty() {
                let _ = writeln!(self.helpers, "static bool {key}_eq(const void *a, const void *b) {{ (void)a; (void)b; return {eq}; }}\nstatic uint64_t {key}_hs(const void *p) {{ (void)p; return {hash}; }}");
                (format!("{key}_eq"), format!("{key}_hs"))
            } else {
                self.helpers.push_str(&extra);
                (format!("{key}_eq2"), format!("{key}_hs2"))
            };
            let _ = writeln!(
                self.helpers,
                "static void {key}_ts(bm_sb *sb, const void *p) {{ (void)p; {ts}; }}\nstatic void {key}_in(bm_sb *sb, const void *p, int depth) {{ (void)p; (void)depth; {ins}; }}\nstatic const bm_type {key} = {{ sizeof({ct}), {rt}, {rl}, {eq_fn}, {hash_fn}, {key}_ts, {key}_in }};"
            );
        }
        format!("&{key}")
    }

    fn desc_key(&self, t: TyId) -> String {
        format!("TY{}", t.0)
    }

    // ------------------------------------------------------------ functions

    /// C name of a function instance, queueing it for emission.
    pub(crate) fn instance(&mut self, m: u32, item: u32, subst: FxMap<u32, TyId>) -> String {
        let mut key_args: Vec<(u32, TyId)> = subst.iter().map(|(&k, &v)| (k, v)).collect();
        key_args.sort();
        let key = (m, item, key_args);
        if let Some(n) = self.instances.get(&key) {
            return n.clone();
        }
        let ItemKind::Function(f) = &self.ast(m).items[item as usize].kind else { unreachable!() };
        let name = self.sym(f.name);
        let base = if name == "<script>" { format!("f{m}_script_") } else { format!("f{m}_{name}") };
        let cname = if subst.is_empty() { base } else { format!("{base}_{}", self.instances.len()) };
        self.instances.insert(key, cname.clone());
        // Prototype now, body later.
        let sig = self.c.sigs[&(m, item)].clone();
        if self.is_async_fn(m, item) {
            self.declare_async(&cname, &sig.params, &subst);
        } else {
            let proto = self.fn_proto(&cname, &sig.params, sig.ret, &subst, false);
            let _ = writeln!(self.protos, "static {proto};");
        }
        self.queue.push(Instance { m, item, subst, cname: cname.clone() });
        cname
    }

    /// `ret name(params)` for a function with the given (uninstantiated) signature.
    pub(crate) fn fn_proto(&mut self, cname: &str, params: &[FnParam], ret: TyId, subst: &FxMap<u32, TyId>, with_env: bool) -> String {
        let ret = self.c.types.subst(ret, subst);
        let rct = if ret == VOID { "void".to_string() } else { self.ctype(ret) };
        let mut ps: Vec<String> = Vec::new();
        if with_env {
            ps.push("bm_env *env_".into());
        }
        for (i, p) in params.iter().enumerate() {
            let t = self.c.types.subst(p.ty, subst);
            let ct = self.ctype(t);
            ps.push(if p.inout { format!("{ct} *p{i}") } else { format!("{ct} p{i}") });
        }
        if ps.is_empty() {
            ps.push("void".into());
        }
        format!("{rct} {cname}({})", ps.join(", "))
    }

    /// A `bm_fn` value calling a (non-generic) module function.
    pub(crate) fn fn_value(&mut self, m: u32, item: u32) -> String {
        let cname = self.instance(m, item, FxMap::default());
        if let Some(n) = self.fn_values.get(&cname) {
            return format!("((bm_fn){{ (void *){n}, NULL }})");
        }
        let sig = self.c.sigs[&(m, item)].clone();
        let wname = format!("fv_{cname}");
        let proto = self.fn_proto(&wname, &sig.params, sig.ret, &FxMap::default(), true);
        let args: Vec<String> = (0..sig.params.len()).map(|i| format!("p{i}")).collect();
        let call = if self.is_async_fn(m, item) { format!("{cname}_spawn({})", args.join(", ")) } else { format!("{cname}({})", args.join(", ")) };
        let body = if sig.ret == VOID { format!("{call};") } else { format!("return {call};") };
        let _ = writeln!(self.protos, "static {proto};");
        let _ = writeln!(self.funcs, "static {proto} {{ (void)env_; {body} }}");
        self.fn_values.insert(cname, wname.clone());
        format!("((bm_fn){{ (void *){wname}, NULL }})")
    }

    fn emit_function(&mut self, inst: Instance) {
        if self.is_async_fn(inst.m, inst.item) {
            self.emit_async_function(inst);
            return;
        }
        let ItemKind::Function(f) = &self.ast(inst.m).items[inst.item as usize].kind else { return };
        let sig = self.c.sigs[&(inst.m, inst.item)].clone();
        let proto = self.fn_proto(&inst.cname, &sig.params, sig.ret, &inst.subst, false);
        let params: Vec<(u32, TyId, bool)> = f.params.iter().zip(&sig.params).map(|(p, fp)| (p.span.start, self.c.types.subst(fp.ty, &inst.subst), fp.inout)).collect();
        let ret = self.c.types.subst(sig.ret, &inst.subst);
        // Leak-free `inout` array parameters arrive uniquely owned (callers guarantee it).
        let mut entry_unique = Vec::new();
        for (i, (key, ty, inout)) in params.iter().enumerate() {
            if *inout && matches!(self.tget(*ty), Ty::Array(_)) && self.inout_leak_free(inst.m, inst.item, i) {
                entry_unique.push(*key);
            }
        }
        let code = self.function_body(inst.m, inst.subst.clone(), &params, ret, body::FnBodyKind::Block(f.body), Some(entry_unique), None, None);
        let _ = writeln!(self.funcs, "static {proto} {{\n{code}}}\n");
    }

    /// Prints an error that escaped `main` (stderr) or fails the running test.
    fn uncaught_fn(&mut self) -> String {
        let err = self.c.error_class();
        let text = if err == ERROR { "bm_sb_push_cstr(sb, \"Error\")".to_string() } else {
            let ct = self.ctype(err);
            self.string_code(err, &format!("(({ct})e)"))
        };
        let _ = writeln!(self.protos, "static void bmg_uncaught(void);");
        format!(
            "static void bmg_uncaught(void) {{\n    void *e = bmg_err; bmg_err = NULL;\n    bm_sb sbv = {{0}}; bm_sb *sb = &sbv;\n    bm_sb_push_cstr(sb, \"uncaught \");\n    {text};\n    bm_sb_push_char(sb, '\\0');\n    bm_out_flush();\n    if (bm_test_active()) bm_trap(sbv.data, NULL);\n    fprintf(stderr, \"%s\\n\", sbv.data);\n    fflush(stderr);\n}}\n"
        )
    }

    fn test_fn(&mut self, m: u32, arrow: ExprId) -> String {
        let name = self.fresh("test_");
        let ast::ExprKind::Arrow(f) = &self.ast(m).expr(arrow).kind else { return name };
        let body = match &f.body {
            ast::ArrowBody::Block(b) => body::FnBodyKind::Block(*b),
            ast::ArrowBody::Expr(e) => body::FnBodyKind::Expr(*e),
        };
        let code = self.function_body(m, FxMap::default(), &[], VOID, body, None, None, None);
        let _ = writeln!(self.funcs, "static void {name}_body(void) {{\n{code}}}\n");
        let _ = writeln!(self.funcs, "static void {name}(void) {{ {name}_body(); if (bmg_err) bmg_uncaught(); }}\n");
        let _ = writeln!(self.protos, "static void bmg_uncaught(void);");
        name
    }

    // ------------------------------------------------------------ module constants

    /// C expression for a module constant, emitting its global and initializer on first use.
    pub(crate) fn const_ref(&mut self, m: u32, item: u32) -> Val {
        let ty = self.c.consts[&(m, item)];
        let ItemKind::Const { name, init, .. } = &self.ast(m).items[item as usize].kind else { unreachable!() };
        let gname = format!("g{m}_{}", self.sym(*name));
        if self.consts_done.insert((m, item)) {
            let ct = self.ctype(ty);
            let _ = writeln!(self.protos, "static {ct} {gname};");
            // An initializer that awaits runs inline in the (async) script body instead.
            if self.script_module == Some(m) && asyncfn::has_await(self.ast(m), *init) {
                return Val::plain(gname, ty);
            }
            // Initialize dependencies first (their `const_ref` calls happen while emitting this initializer).
            let code = self.function_body(m, FxMap::default(), &[], ty, body::FnBodyKind::Expr(*init), None, None, None);
            let fname = format!("init_{gname}");
            let _ = writeln!(self.funcs, "static {ct} {fname}(void) {{\n{code}}}\n");
            // A script initializes its own variables where they're declared.
            if self.script_module != Some(m) {
                let _ = writeln!(self.const_init, "    {gname} = {fname}();");
            }
        }
        Val::plain(gname, ty)
    }

    pub(crate) fn ident_fact(&self, m: u32, e: ExprId) -> Option<IdentFact> {
        self.facts(m).idents.get(&e).copied()
    }
}

/// A C string literal for arbitrary bytes.
pub(crate) fn c_string(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() + 2);
    out.push('"');
    for &b in bytes {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            b'?' => out.push_str("\\?"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                let _ = write!(out, "\\{:03o}", b);
            }
        }
    }
    out.push('"');
    out
}

/// Small helpers used by generated code (after the runtime).
const PRELUDE: &str = r#"
typedef uint8_t bm_unit;
/* String literals are real bm_strbuf objects (GNU static flexible-array initializer), so the
 * program can be compiled with strict aliasing. */
#define BMG_STR_LIT(name, text) static bm_strbuf name = { -1, sizeof(text) - 1, text }
#define BMG_LIT(name) ((bm_str){&(name)})
/* Small-object allocator for boxes and cells (sizes known at every call site): per-size-class
 * free lists refilled from 64 KiB slabs. Memory is reused, never returned to malloc. */
enum { BMG_CLASSES = 33 };
typedef struct bmg_free_node { struct bmg_free_node *next; } bmg_free_node;
static bmg_free_node *bmg_bins[BMG_CLASSES];
static __attribute__((noinline)) void *bmg_refill(size_t c) {
    size_t sz = c * 16, n = 65536 / sz;
    char *slab = bm_alloc(n * sz);
    for (size_t i = n - 1; i >= 1; i--) {
        bmg_free_node *f = (bmg_free_node *)(void *)(slab + i * sz);
        f->next = bmg_bins[c];
        bmg_bins[c] = f;
    }
    return slab;
}
#if defined(__SANITIZE_ADDRESS__) || (defined(__has_feature) && __has_feature(address_sanitizer))
#define BMG_PLAIN_ALLOC 1 /* let AddressSanitizer see every allocation */
#endif
static inline void *bmg_alloc_small(size_t size) {
#ifdef BMG_PLAIN_ALLOC
    return bm_alloc(size);
#endif
    size_t c = (size + 15) >> 4;
    if (__builtin_expect(c >= BMG_CLASSES, 0)) return bm_alloc(size);
    bmg_free_node *f = bmg_bins[c];
    if (__builtin_expect(f != NULL, 1)) { bmg_bins[c] = f->next; return f; }
    return bmg_refill(c);
}
/* JSON.stringify indentation: a newline and `lvl` copies of `ind` (nothing when compact). */
static void bmg_js_nl(bm_sb *sb, bm_str ind, int lvl) {
    if (!ind.p->len) return;
    bm_sb_push_char(sb, '\n');
    for (int i = 0; i < lvl; i++) bm_sb_push(sb, ind.p->data, (size_t)ind.p->len);
}
static bm_str bmg_js_spaces(bm_int n) {
    static const char sp[] = "          ";
    if (n <= 0) return BM_EMPTY_STR;
    return bm_str_from(sp, (size_t)(n > 10 ? 10 : n));
}
#if defined(__APPLE__)
#define BMG_PLATFORM "darwin"
#elif defined(_WIN32)
#define BMG_PLATFORM "win32"
#else
#define BMG_PLATFORM "linux"
#endif
/* The error being thrown (a class instance extending Error), or NULL. Calls that can throw are
 * followed by a check; `try` blocks jump to their handler, other code returns early. */
static void *bmg_err;
/* An async function waiting at an `await`: it returns "not finished" (see asyncfn.rs). */
#define BM_SUSPEND return false
/* Interface values: data (object, boxed record copy, or cell) + itab (retain/release/print, then
 * one thunk per member). */
typedef struct bmg_itab {
    void (*retain)(void *p);
    void (*release)(void *p);
    void (*inspect)(bm_sb *sb, void *p, int depth);
    void (*to_str)(bm_sb *sb, void *p);
} bmg_itab;
typedef struct bm_iface { void *p; const bmg_itab *t; } bm_iface;
static inline void bm_iface_retain(bm_iface v) { if (v.t) v.t->retain(v.p); }
static inline void bm_iface_release(bm_iface v) { if (v.t) v.t->release(v.p); }
/* Class instances: a 16-byte header, then fields (a subclass embeds its base first). */
typedef struct bmg_obj { int32_t rc; int32_t weak; uint32_t cid; uint32_t flags; } bmg_obj;
static void bmg_obj_drop(void *p);
static void bmg_obj_free(void *p);
static void bmg_obj_inspect(bm_sb *sb, void *p, int depth);
#define bmg_obj_init(o, id) (*(bmg_obj *)(void *)(o) = (bmg_obj){1, 0, (id), 0})
static inline void bmg_obj_retain(void *p) { if (p) ((bmg_obj *)p)->rc++; }
/* A function value adapted to another function type: the environment holds the original. */
typedef struct bmg_fnbox { bm_env h; bm_fn f; } bmg_fnbox;
static void bmg_fnbox_drop(bm_env *e) { bm_env_release(((bmg_fnbox *)e)->f.env); }
static inline void bmg_obj_release(void *p) { if (p && --((bmg_obj *)p)->rc == 0) bmg_obj_drop(p); }
static inline void bmg_weak_retain(void *p) { if (p) ((bmg_obj *)p)->weak++; }
static inline void bmg_weak_release(void *p) { if (p && --((bmg_obj *)p)->weak == 0 && ((bmg_obj *)p)->rc <= 0) bmg_obj_free(p); }
static inline void bmg_free_small(void *p, size_t size) {
#ifdef BMG_PLAIN_ALLOC
    bm_free(p); return;
#endif
    size_t c = (size + 15) >> 4;
    if (__builtin_expect(c >= BMG_CLASSES, 0)) { bm_free(p); return; }
    bmg_free_node *f = p;
    f->next = bmg_bins[c];
    bmg_bins[c] = f;
}
/* ---- Cycle collector for `cyclic class` objects (only they pay for it) ----
 * Cyclic objects live in a list, with a 24-byte prefix before the header. A collection counts,
 * for each cyclic object, the references it gets from other cyclic objects; any object with more
 * references than that is referenced from outside (a variable, a temporary, an acyclic object)
 * and is live, as is everything it reaches. The rest is garbage: unreachable cycles.
 * Copy-on-write buffers (arrays, maps, boxes) reachable from cyclic objects are graph nodes too,
 * so a buffer shared by two objects isn't counted twice. */
typedef struct bmg_cyc { struct bmg_cyc *prev, *next; int64_t gc; } bmg_cyc;
enum { BMG_CYCLIC = 1, BMG_COLLECTING = 2, BMG_REACHED = 4 };
static bmg_cyc bmg_cyc_head = { &bmg_cyc_head, &bmg_cyc_head, 0 };
static int64_t bmg_cyc_count, bmg_cyc_since, bmg_cyc_limit = 10000;
static int bmg_gc_phase; /* 1: count internal references; 2: mark what's reachable */
#define BMG_CYC(p) ((bmg_cyc *)(void *)((char *)(p) - sizeof(bmg_cyc)))
#define BMG_OBJ(c) ((bmg_obj *)(void *)((char *)(c) + sizeof(bmg_cyc)))
static void bmg_cyc_collect(void);
static void bmg_obj_traverse(void *p);
static void bmg_obj_dropfields(void *p);
static inline void *bmg_cyc_alloc(size_t size) {
    if (__builtin_expect(++bmg_cyc_since > bmg_cyc_limit, 0)) bmg_cyc_collect();
    bmg_cyc *c = bmg_alloc_small(size + sizeof(bmg_cyc));
    c->next = bmg_cyc_head.next; c->prev = &bmg_cyc_head; bmg_cyc_head.next->prev = c; bmg_cyc_head.next = c;
    bmg_cyc_count++;
    return c + 1;
}
static inline void bmg_cyc_unlink(void *p) { bmg_cyc *c = BMG_CYC(p); c->prev->next = c->next; c->next->prev = c->prev; bmg_cyc_count--; }
static inline void bmg_cyc_free(void *p, size_t size) { bmg_free_small(BMG_CYC(p), size + sizeof(bmg_cyc)); }
typedef void (*bmg_gv_fn)(void *buf, int64_t len);
typedef struct { void *buf; int64_t internal; int64_t len; bmg_gv_fn fn; int reached; } bmg_gcb;
static bmg_gcb *bmg_gcb_tab; static size_t bmg_gcb_cap, bmg_gcb_n;
static void **bmg_gc_stack; static size_t bmg_gc_sn, bmg_gc_scap;
static bmg_gcb *bmg_gcb_find(void *buf, int *fresh) {
    if ((bmg_gcb_n + 1) * 2 > bmg_gcb_cap) {
        size_t oc = bmg_gcb_cap, nc = oc ? oc * 2 : 1024;
        bmg_gcb *old = bmg_gcb_tab;
        bmg_gcb_tab = calloc(nc, sizeof(bmg_gcb));
        if (!bmg_gcb_tab) bm_trap("out of memory", "cycle collector");
        bmg_gcb_cap = nc;
        for (size_t i = 0; i < oc; i++) if (old[i].buf) {
            size_t h = ((uintptr_t)old[i].buf >> 4) * 0x9E3779B97F4A7C15ull & (nc - 1);
            while (bmg_gcb_tab[h].buf) h = (h + 1) & (nc - 1);
            bmg_gcb_tab[h] = old[i];
        }
        free(old);
    }
    size_t h = ((uintptr_t)buf >> 4) * 0x9E3779B97F4A7C15ull & (bmg_gcb_cap - 1);
    while (bmg_gcb_tab[h].buf && bmg_gcb_tab[h].buf != buf) h = (h + 1) & (bmg_gcb_cap - 1);
    *fresh = bmg_gcb_tab[h].buf == NULL;
    if (*fresh) { bmg_gcb_tab[h].buf = buf; bmg_gcb_n++; }
    return &bmg_gcb_tab[h];
}
static void bmg_gc_push(void *p) {
    if (bmg_gc_sn == bmg_gc_scap) {
        bmg_gc_scap = bmg_gc_scap ? bmg_gc_scap * 2 : 1024;
        bmg_gc_stack = realloc(bmg_gc_stack, bmg_gc_scap * sizeof(void *));
        if (!bmg_gc_stack) bm_trap("out of memory", "cycle collector");
    }
    bmg_gc_stack[bmg_gc_sn++] = p;
}
/* A strong reference from a cyclic object (or one of its buffers) to a class instance. */
static inline void bmg_gc_obj(void *p) {
    if (!p) return;
    bmg_obj *h = p;
    if (!(h->flags & BMG_CYCLIC)) return;
    if (bmg_gc_phase == 1) BMG_CYC(p)->gc--;
    else if (!(h->flags & BMG_REACHED)) { h->flags |= BMG_REACHED; bmg_gc_push(p); }
}
/* A buffer reachable from a cyclic object: returns true when its elements should be visited now. */
static bool bmg_gc_buf(void *buf, int64_t len, bmg_gv_fn fn) {
    if (!buf || *(int64_t *)buf < 0) return false;
    int fresh;
    bmg_gcb *b = bmg_gcb_find(buf, &fresh);
    if (fresh) { b->len = len; b->fn = fn; }
    if (bmg_gc_phase == 1) { b->internal++; return fresh; }
    if (b->reached) return false;
    b->reached = 1;
    return true;
}
static void bmg_cyc_collect(void) {
    bmg_cyc_since = 0;
    if (bmg_gcb_tab) memset(bmg_gcb_tab, 0, bmg_gcb_cap * sizeof(bmg_gcb));
    bmg_gcb_n = 0;
    for (bmg_cyc *c = bmg_cyc_head.next; c != &bmg_cyc_head; c = c->next) c->gc = BMG_OBJ(c)->rc;
    bmg_gc_phase = 1;
    for (bmg_cyc *c = bmg_cyc_head.next; c != &bmg_cyc_head; c = c->next) bmg_obj_traverse(BMG_OBJ(c));
    bmg_gc_phase = 2;
    bmg_gc_sn = 0;
    for (bmg_cyc *c = bmg_cyc_head.next; c != &bmg_cyc_head; c = c->next)
        if (c->gc > 0) { BMG_OBJ(c)->flags |= BMG_REACHED; bmg_gc_push(BMG_OBJ(c)); }
    for (size_t i = 0; i < bmg_gcb_cap; i++) {
        bmg_gcb *b = &bmg_gcb_tab[i];
        if (b->buf && !b->reached && *(int64_t *)b->buf > b->internal) { b->reached = 1; b->fn(b->buf, b->len); }
    }
    while (bmg_gc_sn) {
        void *p = bmg_gc_stack[--bmg_gc_sn];
        bmg_obj_traverse(p);
    }
    bmg_gc_phase = 0;
    /* Garbage: not reached. Unlink it, release its fields (freeing what only it referenced; its
     * own count reaching zero is ignored while it's being collected), then free it. */
    bmg_cyc *garbage = NULL;
    for (bmg_cyc *c = bmg_cyc_head.next, *next; c != &bmg_cyc_head; c = next) {
        next = c->next;
        bmg_obj *h = BMG_OBJ(c);
        if (h->flags & BMG_REACHED) { h->flags &= ~BMG_REACHED; continue; }
        h->flags |= BMG_COLLECTING;
        bmg_cyc_unlink(h);
        c->next = garbage;
        garbage = c;
    }
    for (bmg_cyc *c = garbage; c; c = c->next) BMG_OBJ(c)->weak++; /* pinned while fields are released */
    for (bmg_cyc *c = garbage; c; c = c->next) bmg_obj_dropfields(BMG_OBJ(c));
    for (bmg_cyc *c = garbage, *next; c; c = next) {
        next = c->next;
        bmg_obj *h = BMG_OBJ(c);
        h->rc = 0;
        h->flags &= ~BMG_COLLECTING;
        if (--h->weak == 0) bmg_obj_free(h);
    }
    int64_t live = bmg_cyc_count * 2;
    bmg_cyc_limit = live > 10000 ? live : 10000;
}
/* Slow paths take arrays by value and return the updated value, so the array itself never
 * escapes: the C compiler keeps its length (and pointer) in registers and can reason about it. */
static __attribute__((noinline)) bm_arr bmg_push_slow(bm_arr a, const bm_type *t, void *elem) { bm_arr_push(&a, t, elem); return a; }
static __attribute__((noinline)) bm_arrbuf *bmg_clone_buf(bm_arr a, const bm_type *t) { bm_arr_make_unique(&a, t, 0); return a.p; }
/* Makes the buffer unique (copy-on-write) without changing the length. */
static inline void bmg_make_unique(bm_arr *a, const bm_type *t) {
    if (a->p && __builtin_expect(a->p->rc != 1, 0)) a->p = bmg_clone_buf(*a, t);
}
/* Typed push: inline fast path when the buffer is unique with spare capacity. */
#define BMG_PUSH(T, arr, desc, val) do { bm_arr *bmp_a = (arr); T bmp_v = (val); bm_arrbuf *bmp_p = bmp_a->p; \
    if (__builtin_expect(bmp_p && bmp_p->rc == 1 && bmp_a->len < bmp_p->cap, 1)) ((T *)(void *)bmp_p->data)[bmp_a->len++] = bmp_v; \
    else *bmp_a = bmg_push_slow(*bmp_a, (desc), &bmp_v); } while (0)
/* Mutable element access: copy-on-write, then a bounds-checked pointer. */
static inline void *bmg_at_mut(bm_arr *a, const bm_type *t, size_t size, bm_int i, const char *loc) {
    bmg_make_unique(a, t);
    return bm_arr_at(*a, size, i, loc);
}
/* LSD radix sort of 64-bit keys, 11-bit digits, skipping digits every key shares.
 * `idx` (optional) is permuted alongside the keys. Stable. */
static void bmg_radix64(uint64_t *keys, int64_t *idx, bm_int n) {
    if (n < 2) return;
    enum { BITS = 11, B = 1 << BITS, PASSES = 6 };
    size_t *hist = calloc((size_t)PASSES * B, sizeof(size_t));
    if (!hist) bm_trap("out of memory", "sort");
    for (bm_int i = 0; i < n; i++) {
        uint64_t k = keys[i];
        for (int p = 0; p < PASSES; p++) hist[p * B + ((k >> (p * BITS)) & (B - 1))]++;
    }
    uint64_t *k2 = bm_alloc((size_t)n * sizeof(uint64_t));
    int64_t *i2 = idx ? bm_alloc((size_t)n * sizeof(int64_t)) : NULL;
    uint64_t *ks = keys, *kd = k2;
    int64_t *is = idx, *id = i2;
    for (int p = 0; p < PASSES; p++) {
        size_t *h = hist + p * B;
        int shift = p * BITS;
        if (h[(ks[0] >> shift) & (B - 1)] == (size_t)n) continue;
        size_t sum = 0;
        for (int b = 0; b < B; b++) { size_t c = h[b]; h[b] = sum; sum += c; }
        if (idx) {
            for (bm_int i = 0; i < n; i++) { uint64_t k = ks[i]; size_t pos = h[(k >> shift) & (B - 1)]++; kd[pos] = k; id[pos] = is[i]; }
            int64_t *ti = is; is = id; id = ti;
        } else {
            for (bm_int i = 0; i < n; i++) { uint64_t k = ks[i]; kd[h[(k >> shift) & (B - 1)]++] = k; }
        }
        uint64_t *tk = ks; ks = kd; kd = tk;
    }
    if (ks != keys) memcpy(keys, ks, (size_t)n * sizeof(uint64_t));
    if (idx && is != idx) memcpy(idx, is, (size_t)n * sizeof(int64_t));
    bm_free(k2);
    if (i2) bm_free(i2);
    free(hist);
}
/* Order-preserving 64-bit key for a double under the comparator `a - b`:
 * both zeros share a key (they compare equal), NaN sorts last. */
static inline uint64_t bmg_f64_key(double x) {
    uint64_t u;
    if (x == 0) u = 0;
    else if (x != x) u = 0x7FF8000000000000ull;
    else memcpy(&u, &x, 8);
    return (u >> 63) ? ~u : (u ^ 0x8000000000000000ull);
}
/* xs.sort((a, b) => a - b) / (b - a) on f64[]: radix sort of keys, decoded back; zeros keep
 * their original relative order (their signs are replayed in encounter order). */
static void bmg_sort_f64(double *a, bm_int n, bool desc) {
    if (n < 2) return;
    uint64_t *k = bm_alloc((size_t)n * sizeof(uint64_t));
    uint8_t *zs = NULL;
    bm_int nz = 0;
    for (bm_int i = 0; i < n; i++) {
        double x = a[i];
        if (x == 0) {
            if (!zs) zs = bm_alloc((size_t)n);
            zs[nz++] = signbit(x) ? 1 : 0;
        }
        uint64_t key = bmg_f64_key(x);
        k[i] = desc ? ~key : key;
    }
    bmg_radix64(k, NULL, n);
    uint64_t kz = desc ? ~0x8000000000000000ull : 0x8000000000000000ull;
    bm_int zi = 0;
    for (bm_int i = 0; i < n; i++) {
        uint64_t key = desc ? ~k[i] : k[i];
        if (k[i] == kz) { a[i] = zs[zi++] ? -0.0 : 0.0; continue; }
        uint64_t u = (key >> 63) ? (key ^ 0x8000000000000000ull) : ~key;
        memcpy(&a[i], &u, 8);
    }
    bm_free(k);
    if (zs) bm_free(zs);
}

#ifdef BARM_UNCHECKED
/* --unchecked: two's-complement wrapping (defined behaviour, like Rust release builds). */
#define BM_ADD(T, a, b, loc) ({ T bm__r; (void)__builtin_add_overflow((a), (b), &bm__r); bm__r; })
#define BM_SUB(T, a, b, loc) ({ T bm__r; (void)__builtin_sub_overflow((a), (b), &bm__r); bm__r; })
#define BM_MUL(T, a, b, loc) ({ T bm__r; (void)__builtin_mul_overflow((a), (b), &bm__r); bm__r; })
#else
#define BM_ADD(T, a, b, loc) ({ T bm__r; if (__builtin_expect(__builtin_add_overflow((a), (b), &bm__r), 0)) bm_trap("integer overflow in +", loc); bm__r; })
#define BM_SUB(T, a, b, loc) ({ T bm__r; if (__builtin_expect(__builtin_sub_overflow((a), (b), &bm__r), 0)) bm_trap("integer overflow in -", loc); bm__r; })
#define BM_MUL(T, a, b, loc) ({ T bm__r; if (__builtin_expect(__builtin_mul_overflow((a), (b), &bm__r), 0)) bm_trap("integer overflow in *", loc); bm__r; })
#endif
#define BM_REM(T, a, b, loc) ({ T bm__b = (b); if (bm__b == 0) bm_trap("integer remainder by zero", loc); T bm__a = (a); (bm__b == -1) ? (T)0 : (T)(bm__a % bm__b); })
#define BM_UREM(T, a, b, loc) ({ T bm__b = (b); if (bm__b == 0) bm_trap("integer remainder by zero", loc); (T)((a) % bm__b); })
#define BM_NEG(T, a, loc) ({ T bm__r; if (__builtin_sub_overflow((T)0, (a), &bm__r)) bm_trap("integer overflow in unary -", loc); bm__r; })
#define BM_CONV(T, v, lo, hi, loc) ({ __typeof__(v) bm__v = (v); if (bm__v < (lo) || bm__v > (hi)) bm_trap("integer conversion out of range", loc); (T)bm__v; })
static inline bm_int bm_pow_int(bm_int b, bm_int e, const char *loc) {
    if (e < 0) bm_trap("negative integer exponent (use f64 for fractional powers)", loc);
    bm_int r = 1;
    while (e > 0) {
        if (e & 1) { if (__builtin_mul_overflow(r, b, &r)) bm_trap("integer overflow in **", loc); }
        e >>= 1;
        if (e > 0 && __builtin_mul_overflow(b, b, &b)) bm_trap("integer overflow in **", loc);
    }
    return r;
}
static inline double bm_min_f64(double a, double b) { return (a != a || b != b) ? (0.0 / 0.0) : (a < b ? a : (a > b ? b : (a == 0 && b == 0 ? (signbit(a) ? a : b) : a))); }
static inline double bm_max_f64(double a, double b) { return (a != a || b != b) ? (0.0 / 0.0) : (a > b ? a : (a < b ? b : (a == 0 && b == 0 ? (signbit(a) ? b : a) : a))); }
"#;
