//! Native execution tests: each tests/run/<name>.barm is compiled (C backend) and run; stdout must
//! equal tests/run/<name>.stdout. Most expectations are generated by running the same program
//! under Node (scripts/barm2js.sh); `native_*` tests cover Barm-only semantics and are hand-written.
//! A case with a `.stderr` file must fail, and its stderr must contain that file's text.
//! Also runs every `test(...)` in examples/.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..").canonicalize().unwrap();
    let dir = root.join("tests/run");
    let mut cases: Vec<PathBuf> = std::fs::read_dir(&dir).unwrap().flatten().map(|e| e.path()).filter(|p| p.extension().map(|e| e == "barm").unwrap_or(false)).collect();
    cases.sort();
    let mut failed = Vec::new();
    for case in &cases {
        let name = case.file_stem().unwrap().to_string_lossy().into_owned();
        let opts = barm::build::Options { mode: barm::codegen::Mode::Run, unchecked: false, opt: "-O1".into(), emit_c: None };
        let built = match barm::build::build(std::slice::from_ref(case), &root, &opts) {
            Ok(b) => b,
            Err(barm::build::BuildError::Diagnostics(sm, d)) => {
                failed.push(format!("{name}: build failed\n{}", barm::diag::render_text(&d, &sm)));
                continue;
            }
            Err(barm::build::BuildError::Message(m)) => {
                failed.push(format!("{name}: {m}"));
                continue;
            }
        };
        let out = Command::new(&built.binary).output().expect("run binary");
        let actual = String::from_utf8_lossy(&out.stdout).into_owned();
        let expected = std::fs::read_to_string(case.with_extension("stdout")).unwrap_or_default();
        // A `.stderr` file marks a program that must fail, printing that text.
        if let Ok(err) = std::fs::read_to_string(case.with_extension("stderr")) {
            let stderr = String::from_utf8_lossy(&out.stderr);
            if actual != expected || out.status.success() || !stderr.contains(err.trim()) {
                failed.push(format!("{name}: expected a failure with `{}` (exit {:?})\n--- stdout\n{actual}--- stderr\n{stderr}", err.trim(), out.status.code()));
            }
            continue;
        }
        if actual != expected || !out.status.success() {
            failed.push(format!("{name}: output differs (exit {:?})\n--- expected\n{expected}--- actual\n{actual}{}", out.status.code(), String::from_utf8_lossy(&out.stderr)));
        }
    }
    // Every test in examples/ must pass natively.
    let opts = barm::build::Options { mode: barm::codegen::Mode::Test, unchecked: false, opt: "-O1".into(), emit_c: None };
    let examples = root.join("examples");
    match barm::build::build(&[examples], &root, &opts) {
        Ok(b) => {
            let out = Command::new(&b.binary).output().expect("run tests");
            if !out.status.success() {
                failed.push(format!("examples tests failed:\n{}", String::from_utf8_lossy(&out.stdout)));
            }
        }
        Err(_) => failed.push("examples: build failed".into()),
    }
    for f in &failed {
        eprintln!("{f}\n");
    }
    println!("run: {} programs, {} failed", cases.len(), failed.len());
    if !failed.is_empty() {
        std::process::exit(1);
    }
}
