//! Every diagnostic code with a one-line summary, for `barm explain`.

pub const CODES: &[(&str, &str)] = &[
    ("L0001", "Unexpected character in the source."),
    ("L0002", "Unterminated string or template literal."),
    ("L0003", "Unterminated block comment."),
    ("L0004", "Invalid escape sequence in a string."),
    ("L0005", "Integer literal doesn't fit in 64 bits."),
    ("P0001", "A specific token was expected here."),
    ("P0002", "Statements end with `;` or a line break."),
    ("P0003", "A type was expected here."),
    ("P0004", "An expression was expected here."),
    ("P0005", "Declare one variable or constant per statement."),
    ("P0006", "Imports, types, interfaces and functions are declared at the top level of a module."),
    ("P0007", "Array holes (`[1, , 2]`) are not supported."),
    ("P0201", "The top level holds declarations, `const`s and `test(...)` calls only; program logic goes in `function main()`."),
    ("P0202", "`test(...)` is only allowed at the top level of a module."),
    ("N0001", "Unknown name. Check the spelling, the imports, and that it's declared before use in this scope."),
    ("N0002", "Unknown type name."),
    ("N0003", "The name is already declared in this scope."),
    ("N0004", "Two tests in one module have the same name."),
    ("N0005", "Built-in type names can't be redeclared."),
    ("N0006", "A field or member is listed twice."),
    ("N0007", "A type alias refers to itself without a record or array in between (e.g. `type A = A | int`)."),
    ("N0101", "The imported module file doesn't exist. Paths are relative to the importing file, without extension."),
    ("N0102", "The module has no export with that name. Only declarations marked `export` can be imported."),
    ("N0103", "The standard library isn't available yet (planned for M3)."),
    ("N0104", "Only relative imports (`./x`, `../x`) are supported; there is no npm."),
    ("N0105", "Imports name Barm modules without a file extension."),
    ("T0001", "Type mismatch: the value's type isn't assignable to the expected type. `int` widens to `f64`; nothing else converts implicitly."),
    ("T0010", "Wrong number of type arguments."),
    ("T0020", "Integer literal is out of range for its type."),
    ("T0101", "An object literal is missing required fields. Records are exact: every non-optional field must be given."),
    ("T0102", "An object literal has a field the record type doesn't declare. Records are exact: extra fields are errors."),
    ("T0103", "A string literal isn't one of the union's variants."),
    ("T0104", "When switching over a union of string literals, case labels must be string literals."),
    ("T0107", "The type has no field, property or method with that name."),
    ("T0108", "Only some variants of a union have this field; narrow the union first (`switch (x.kind)` or `if (x.kind === ...)`)."),
    ("T0110", "The value can't be indexed with `[]`."),
    ("T0111", "Array indices must be integers."),
    ("T0120", "The value may be `undefined`. Narrow it (`if (x !== undefined)`), use `?.`, provide a default with `??`, or assert with `!` (traps if undefined)."),
    ("T0201", "Wrong number of arguments in a call."),
    ("T0202", "The value being called is not a function."),
    ("T0203", "A method or built-in function is referenced without calling it."),
    ("T0301", "A type can't be inferred here; add an annotation."),
    ("T0302", "Exported functions must declare their return type: exported signatures are never inferred."),
    ("T0303", "A recursive function needs an explicit return type."),
    ("T0304", "Generic functions can't be used as values yet; wrap the call in an arrow function."),
    ("T0305", "A type argument can't be inferred from the arguments; pass it explicitly (`f<T>(...)`)."),
    ("T0306", "`undefined` alone doesn't determine a type; annotate the binding."),
    ("T0307", "The expression has no value (it is `void`, a namespace, or similar)."),
    ("T0308", "A module constant's value depends on itself."),
    ("T0309", "A `const` needs an initial value."),
    ("T0401", "Conditions must be `bool` (or an optional non-primitive value, tested for presence). There is no implicit truthiness."),
    ("T0402", "`for...of` iterates arrays and sets."),
    ("T0501", "The operator doesn't apply to these operand types."),
    ("T0502", "The comparison can never be true: the two types share no values."),
    ("T0503", "The value can never be `undefined`, so this check or operator is unnecessary."),
    ("T0504", "Different integer types (or integers and `f32`) don't mix implicitly; convert explicitly."),
    ("T0510", "The value can't be converted to text (functions and namespaces aren't printable)."),
    ("T0601", "`as` only narrows (from `unknown` or a union to a member); it never converts values."),
    ("T0701", "`main` takes no parameters and returns `void` or `int` (the exit code)."),
    ("F0101", "Not every path through the function returns a value."),
    ("F0102", "This code can never run."),
    ("F0201", "`break` is only valid inside a loop or `switch`."),
    ("F0202", "`continue` is only valid inside a loop."),
    ("F0301", "A `switch` over a union must handle every variant, or have `default`."),
    ("F0302", "Cases must end with `break`, `return` or `continue`; implicit fallthrough isn't allowed (empty cases may be grouped)."),
    ("F0303", "The same case label appears twice."),
    ("V0001", "A `const` binding (or loop variable) can't be reassigned."),
    ("V0101", "Parameters are read-only. Declare `inout x` (called with `&arg`) to modify the caller's value, or copy it into a `let`."),
    ("V0102", "Module constants are immutable."),
    ("V0103", "Only variables and their fields/elements can be assigned or modified."),
    ("V0104", "A `for...of` variable is a copy of the element; modifying it would not change the collection."),
    ("V0105", "Functions can't be assigned to."),
    ("V0110", "Arguments to `inout` parameters are passed with `&`."),
    ("V0111", "`&` is only used for `inout` parameters."),
    ("V0113", "The same variable can't be passed as two `inout` arguments in one call."),
    ("V0120", "A copy of an array, record or map is changed while the original is still used (or vice versa). TypeScript would share one value; Barm copies. Change the original directly, or copy explicitly (`a.slice()`)."),
    ("V0201", "Mutable module-level state (`let` at the top level) is not allowed."),
    ("X0001", "`any` is not supported. Use a precise type, a union, a generic, or `unknown` with narrowing."),
    ("X0002", "`null` is not supported; `undefined` is the only absent value."),
    ("X0003", "`==`/`!=` are not supported; use `===`/`!==`. There is no type coercion."),
    ("X0004", "`var` is not supported; use `let` or `const`."),
    ("X0005", "`enum` is not supported; use a union of string literals."),
    ("X0006", "Namespaces are not supported; use modules (files)."),
    ("X0007", "`for...in` is not supported; iterate `map.keys()` or use `for...of`."),
    ("X0008", "`delete` is not supported; records have fixed fields. Use `Map.delete` for dynamic keys."),
    ("X0010", "Strings have no `.length`; use `byteLength` (bytes) or `chars().length` (characters)."),
    ("X0011", "Default exports and imports are not supported; export and import by name."),
    ("X0012", "Imports can't be renamed; every name has one spelling across the codebase."),
    ("X0013", "Re-exports and export lists are not supported; put `export` on declarations and import from the declaring module."),
    ("X0014", "Intersection types are not supported; declare a record with all the fields."),
    ("X0015", "Decorators are not supported."),
    ("X0016", "`typeof`/`keyof` in types are not supported; name the type explicitly."),
    ("X0017", "Index signatures, string/computed keys and `[]` on records/maps are not supported; use `.field` on records and `Map.get/set`."),
    ("X0018", "Labels are not supported."),
    ("X0019", "`<T>value` assertions are not supported; use `value as T`."),
    ("X0020", "BigInt is not supported; `int` is 64-bit."),
    ("X0021", "`declare` is not supported."),
    ("X0022", "Tagged template literals are not supported."),
    ("X0024", "The comma operator is not supported."),
    ("X0025", "The `in` operator is not supported; use `map.has(key)`."),
    ("X0026", "`&&=` and `||=` are not supported."),
    ("X0028", "Unary `+` is not supported; convert explicitly."),
    ("X0029", "The `void` operator is not supported."),
    ("X0030", "This TypeScript/JavaScript type isn't supported."),
    ("X0031", "Side-effect imports are not supported; modules have no initialization side effects."),
    ("X0032", "This JavaScript global isn't available in Barm."),
    ("X0033", "`satisfies` is not supported; annotate the binding."),
    ("X0034", "An array's `length` can't be assigned."),
    ("X0035", "Strings can't be indexed by position (UTF-8); use `chars()` or `slice`."),
    ("X0036", "`new Array(...)` is not supported; use an array literal."),
    ("X0037", "Iterate a string's characters with `s.chars()`."),
    ("X0038", "Iterate a map with `keys()` or `values()`."),
    ("X0039", "Truthiness matchers are not supported; compare explicitly."),
    ("C0001", "The native backend doesn't support this construct yet (`barm check` accepts it)."),
    ("C0002", "`barm run`/`barm build` need a `function main()`."),
    ("C0003", "Internal compiler error in the native backend."),
    ("U0001", "Classes are not supported yet (planned for M2)."),
    ("U0003", "`async`/`await` are not supported yet (planned for M6)."),
    ("U0004", "Errors (`throw`, `try`, `throws`, `Error`) and effects (`uses`) are not supported yet (planned for M3)."),
    ("U0005", "Default values for parameters/type parameters are not supported yet."),
    ("U0006", "Destructuring is not supported yet."),
    ("U0007", "Numeric and boolean literal types are not supported yet."),
    ("U0008", "Tuple types are not supported yet; use a record."),
    ("U0010", "Function expressions and nested function declarations are not supported yet; use arrow functions."),
    ("U0011", "Spread and rest syntax are not supported yet."),
    ("U0012", "Methods in object literals are not supported yet."),
    ("U0013", "Generators are not supported yet."),
    ("U0014", "Interface inheritance is not supported yet."),
    ("U0015", "Generic arrow functions and generic interface methods are not supported yet."),
    ("U0016", "Regular expression literals are not supported yet."),
    ("U0017", "This built-in is not supported yet."),
];

pub fn lookup(code: &str) -> Option<&'static str> {
    CODES.iter().find(|(c, _)| c.eq_ignore_ascii_case(code)).map(|(_, s)| *s)
}
